# This workflow will build the StreamDude golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# Note that this requires the VLC development libraries, which are called
# from within a wrapper library (gwyneth 20241207)

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install VLC libvlc-dev libraries
      run: sudo apt-get install -y libvlc-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
#        go-version: '1.23'
        go-version-file: './go.mod'

    - name: Build
      run: CGO_CFLAGS="-I/usr/include" CGO_LDFLAGS="-lvlc" go build -v ./...

    - name: Test
      run: go test -v ./...
